# Generated by Django 4.1.7 on 2023-03-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название модели')),
                ('description', models.TextField(verbose_name='Описание автомобиля')),
                ('image', models.ImageField(upload_to='')),
                ('car_type', models.CharField(choices=[('Для молодых людей', 'Для молодых людей'), ('Для работы', 'Для работы'), ('Для большой семьи', 'Для большой семье'), ('Для путешествий', 'Для путешествий'), ('Для женщин', 'Для женщин'), ('Для успешных', 'Для успешных')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('cost', models.PositiveIntegerField()),
                ('video', models.URLField()),
                ('specifications', models.TextField(null=True, verbose_name='Характеристики')),
                ('model_year', models.TextField(null=True, verbose_name='Модельный год')),
                ('manufacturing_country', models.TextField(null=True, verbose_name='Страна изготовитель')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('rate_stars', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('car_choice_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_object', to='CAR.carshop')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CAR.reviewscar', verbose_name='Родитель')),
            ],
        ),
    ]
